---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ybtzxyhi/menswear.plsofttech.com/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R data $DEPLOYPATH
